trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- template: templates/cucumber-stage.yml
  parameters:
    stageName: Smoke
    displayName: Smoke tests
    jobName: SmokeTests
    jobDisplayName: Run smoke scenarios
    cucumberTag: '@smoke'
    artifactName: smoke-cucumber-html-report