trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- template: templates/cucumber-stage.yml
  parameters:
    stageName: Smoke
    displayName: Smoke tests
    jobName: SmokeTests
    jobDisplayName: Run smoke scenarios
    cucumberTag: '@smoke'
    artifactName: smoke-cucumber-html-report

- template: templates/cucumber-stage.yml
  parameters:
    stageName: Regression
    displayName: Regression tests
    dependsOn: Smoke
    condition: succeededOrFailed()
    jobName: RegressionTests
    jobDisplayName: Run regression scenarios
    cucumberTag: '@regression'
    artifactName: regression-cucumber-html-report